export interface FutureItem {
  symbol: string; // e.g. "RB0", "CU0", "AU0", "IF0", "hf_CL", "hf_GC"
  name: string; // e.g. "螺纹钢连续", "沪铜连续", "沪金连续"
  category: '商品期货' | '股指国债' | '外盘期货';
  subCategory: '黑色系' | '有色金属' | '贵金属' | '能源化工' | '农产品' | '金融期指' | '国债期货' | '全球大宗' | '全球股指';
  exchange: '上期所' | '大商所' | '郑商所' | '中金所' | '能源中心' | '广期所' | 'NYMEX' | 'COMEX' | 'LME' | 'CME';
  unit: string; // e.g. "元/吨", "元/克", "点", "美元/桶", "美元/盎司"
  isGlobal?: boolean;
  relatedSectors: string[]; // 关联A股行业板块
  relatedStocks: { code: string; name: string }[]; // 核心期现联动标的
}

export const FUTURES_DATABASE: FutureItem[] = [
  // 1. 贵金属
  {
    symbol: 'AU0',
    name: '沪金连续',
    category: '商品期货',
    subCategory: '贵金属',
    exchange: '上期所',
    unit: '元/克',
    relatedSectors: ['贵金属', '黄金概念', '珠宝首饰'],
    relatedStocks: [
      { code: '600547', name: '山东黄金' },
      { code: '600489', name: '中金黄金' },
      { code: '601899', name: '紫金矿业' },
      { code: '002155', name: '湖南黄金' },
      { code: '600988', name: '赤峰黄金' },
    ],
  },
  {
    symbol: 'AG0',
    name: '沪银连续',
    category: '商品期货',
    subCategory: '贵金属',
    exchange: '上期所',
    unit: '元/千克',
    relatedSectors: ['贵金属', '白银概念', '有色金属'],
    relatedStocks: [
      { code: '000506', name: '中润资源' },
      { code: '000975', name: '银泰黄金' },
      { code: '600362', name: '江西铜业' },
      { code: '000960', name: '锡业股份' },
    ],
  },

  // 2. 黑色系
  {
    symbol: 'RB0',
    name: '螺纹钢连续',
    category: '商品期货',
    subCategory: '黑色系',
    exchange: '上期所',
    unit: '元/吨',
    relatedSectors: ['钢铁行业', '建筑材料', '基建地产'],
    relatedStocks: [
      { code: '600019', name: '宝钢股份' },
      { code: '000932', name: '华菱钢铁' },
      { code: '600569', name: '安阳钢铁' },
      { code: '000709', name: '河钢股份' },
    ],
  },
  {
    symbol: 'HC0',
    name: '热卷连续',
    category: '商品期货',
    subCategory: '黑色系',
    exchange: '上期所',
    unit: '元/吨',
    relatedSectors: ['钢铁行业', '制造业', '汽车板'],
    relatedStocks: [
      { code: '600019', name: '宝钢股份' },
      { code: '600808', name: '马钢股份' },
      { code: '000778', name: '新兴铸管' },
    ],
  },
  {
    symbol: 'I0',
    name: '铁矿石连续',
    category: '商品期货',
    subCategory: '黑色系',
    exchange: '大商所',
    unit: '元/吨',
    relatedSectors: ['钢铁采选', '黑色金属', '港口航运'],
    relatedStocks: [
      { code: '600495', name: '晋西车轴' },
      { code: '000655', name: '金岭矿业' },
      { code: '600307', name: '酒钢宏兴' },
      { code: '601003', name: '柳钢股份' },
    ],
  },
  {
    symbol: 'J0',
    name: '焦炭连续',
    category: '商品期货',
    subCategory: '黑色系',
    exchange: '大商所',
    unit: '元/吨',
    relatedSectors: ['煤炭开采', '焦化行业', '钢铁冶炼'],
    relatedStocks: [
      { code: '601699', name: '潞安环能' },
      { code: '600971', name: '恒源煤电' },
      { code: '600123', name: '兰花科创' },
      { code: '600985', name: '淮北矿业' },
    ],
  },
  {
    symbol: 'JM0',
    name: '焦煤连续',
    category: '商品期货',
    subCategory: '黑色系',
    exchange: '大商所',
    unit: '元/吨',
    relatedSectors: ['煤炭开采', '炼焦煤', '能源开采'],
    relatedStocks: [
      { code: '600395', name: '盘江股份' },
      { code: '600740', name: '山西焦化' },
      { code: '000983', name: '山西焦煤' },
    ],
  },

  // 3. 有色金属
  {
    symbol: 'CU0',
    name: '沪铜连续',
    category: '商品期货',
    subCategory: '有色金属',
    exchange: '上期所',
    unit: '元/吨',
    relatedSectors: ['有色金属', '铜产业', '电网设备', '新能源车'],
    relatedStocks: [
      { code: '600362', name: '江西铜业' },
      { code: '601899', name: '紫金矿业' },
      { code: '601168', name: '西部矿业' },
      { code: '000878', name: '云南铜业' },
      { code: '000630', name: '铜陵有色' },
    ],
  },
  {
    symbol: 'AL0',
    name: '沪铝连续',
    category: '商品期货',
    subCategory: '有色金属',
    exchange: '上期所',
    unit: '元/吨',
    relatedSectors: ['有色金属', '铝工业', '轻量化汽车', '光伏支架'],
    relatedStocks: [
      { code: '601600', name: '中国铝业' },
      { code: '600219', name: '南山铝业' },
      { code: '000807', name: '云铝股份' },
      { code: '002578', name: '闽发铝业' },
    ],
  },
  {
    symbol: 'ZN0',
    name: '沪锌连续',
    category: '商品期货',
    subCategory: '有色金属',
    exchange: '上期所',
    unit: '元/吨',
    relatedSectors: ['有色金属', '锌冶炼', '镀锌防腐'],
    relatedStocks: [
      { code: '000060', name: '中金岭南' },
      { code: '600497', name: '驰宏锌锗' },
      { code: '000751', name: '锌业股份' },
    ],
  },
  {
    symbol: 'NI0',
    name: '沪镍连续',
    category: '商品期货',
    subCategory: '有色金属',
    exchange: '上期所',
    unit: '元/吨',
    relatedSectors: ['有色金属', '三元锂电池', '不锈钢'],
    relatedStocks: [
      { code: '600478', name: '科力远' },
      { code: '603799', name: '华友钴业' },
      { code: '002340', name: '格林美' },
      { code: '300919', name: '中伟股份' },
    ],
  },
  {
    symbol: 'SN0',
    name: '沪锡连续',
    category: '商品期货',
    subCategory: '有色金属',
    exchange: '上期所',
    unit: '元/吨',
    relatedSectors: ['有色金属', '半导体焊料', '光伏焊带'],
    relatedStocks: [
      { code: '000960', name: '锡业股份' },
      { code: '688599', name: '天合光能' },
      { code: '300037', name: '新宙邦' },
    ],
  },
  {
    symbol: 'LC0',
    name: '碳酸锂连续',
    category: '商品期货',
    subCategory: '有色金属',
    exchange: '广期所',
    unit: '元/吨',
    relatedSectors: ['新能源电池', '锂矿开采', '储能设备'],
    relatedStocks: [
      { code: '002466', name: '天齐锂业' },
      { code: '002460', name: '赣锋锂业' },
      { code: '000792', name: '盐湖股份' },
      { code: '002192', name: '融捷股份' },
      { code: '002240', name: '盛新锂能' },
    ],
  },
  {
    symbol: 'SI0',
    name: '工业硅连续',
    category: '商品期货',
    subCategory: '有色金属',
    exchange: '广期所',
    unit: '元/吨',
    relatedSectors: ['光伏硅料', '有机硅', '半导体材料'],
    relatedStocks: [
      { code: '603260', name: '合盛硅业' },
      { code: '600089', name: '特变电工' },
      { code: '600438', name: '通威股份' },
      { code: '600141', name: '兴发集团' },
    ],
  },

  // 4. 能源化工
  {
    symbol: 'SC0',
    name: '原油连续',
    category: '商品期货',
    subCategory: '能源化工',
    exchange: '能源中心',
    unit: '元/桶',
    relatedSectors: ['石油开采', '油服工程', '炼化精细化工'],
    relatedStocks: [
      { code: '600938', name: '中国海油' },
      { code: '601857', name: '中国石油' },
      { code: '600028', name: '中国石化' },
      { code: '603619', name: '中曼石油' },
      { code: '601808', name: '中海油服' },
    ],
  },
  {
    symbol: 'MA0',
    name: '甲醇连续',
    category: '商品期货',
    subCategory: '能源化工',
    exchange: '郑商所',
    unit: '元/吨',
    relatedSectors: ['煤化工', '精细化工', '甲醇制烯烃'],
    relatedStocks: [
      { code: '600426', name: '华鲁恒升' },
      { code: '600691', name: '阳煤化工' },
      { code: '600989', name: '宝丰能源' },
    ],
  },
  {
    symbol: 'TA0',
    name: 'PTA连续',
    category: '商品期货',
    subCategory: '能源化工',
    exchange: '郑商所',
    unit: '元/吨',
    relatedSectors: ['化纤纺织', '聚酯产业链', '精细化工'],
    relatedStocks: [
      { code: '002493', name: '荣盛石化' },
      { code: '000703', name: '恒逸石化' },
      { code: '600346', name: '恒力石化' },
      { code: '002422', name: '科伦药业' },
    ],
  },
  {
    symbol: 'SA0',
    name: '纯碱连续',
    category: '商品期货',
    subCategory: '能源化工',
    exchange: '郑商所',
    unit: '元/吨',
    relatedSectors: ['玻璃纯碱', '光伏玻璃', '无机盐化工'],
    relatedStocks: [
      { code: '000683', name: '远兴能源' },
      { code: '600409', name: '三友化工' },
      { code: '600078', name: '澄星股份' },
      { code: '000822', name: '山东海化' },
    ],
  },
  {
    symbol: 'FG0',
    name: '玻璃连续',
    category: '商品期货',
    subCategory: '能源化工',
    exchange: '郑商所',
    unit: '元/吨',
    relatedSectors: ['建筑玻璃', '光伏玻璃', '汽车玻璃'],
    relatedStocks: [
      { code: '600586', name: '金晶科技' },
      { code: '601636', name: '旗滨集团' },
      { code: '600876', name: '凯盛新能' },
      { code: '600660', name: '福耀玻璃' },
    ],
  },

  // 5. 金融股指期货 & 国债期货
  {
    symbol: 'IF0',
    name: '沪深300期指连续',
    category: '股指国债',
    subCategory: '金融期指',
    exchange: '中金所',
    unit: '点',
    relatedSectors: ['核心资产', '白马权重', '金融地产', '沪深300ETF'],
    relatedStocks: [
      { code: '600519', name: '贵州茅台' },
      { code: '300750', name: '宁德时代' },
      { code: '601318', name: '中国平安' },
      { code: '000858', name: '五粮液' },
      { code: '600036', name: '招商银行' },
    ],
  },
  {
    symbol: 'IC0',
    name: '中证500期指连续',
    category: '股指国债',
    subCategory: '金融期指',
    exchange: '中金所',
    unit: '点',
    relatedSectors: ['中盘成长', '高端制造', '新材料', '中证500ETF'],
    relatedStocks: [
      { code: '002475', name: '立讯精密' },
      { code: '300124', name: '汇川技术' },
      { code: '002415', name: '海康威视' },
      { code: '600487', name: '亨通光电' },
    ],
  },
  {
    symbol: 'IM0',
    name: '中证1000期指连续',
    category: '股指国债',
    subCategory: '金融期指',
    exchange: '中金所',
    unit: '点',
    relatedSectors: ['小盘题材', '专精特新', '游资短线', '中证1000ETF'],
    relatedStocks: [
      { code: '300017', name: '网宿科技' },
      { code: '300862', name: '蓝盾光电' },
      { code: '688286', name: '敏芯股份' },
      { code: '300684', name: '中石科技' },
    ],
  },
  {
    symbol: 'IH0',
    name: '上证50期指连续',
    category: '股指国债',
    subCategory: '金融期指',
    exchange: '中金所',
    unit: '点',
    relatedSectors: ['超大盘权重', '央国企红利', '银行保险', '上证50ETF'],
    relatedStocks: [
      { code: '601398', name: '工商银行' },
      { code: '601288', name: '农业银行' },
      { code: '601857', name: '中国石油' },
      { code: '601088', name: '中国神华' },
    ],
  },
  {
    symbol: 'T0',
    name: '10年期国债期货',
    category: '股指国债',
    subCategory: '国债期货',
    exchange: '中金所',
    unit: '元',
    relatedSectors: ['固收理财', '银行间债市', '宏观利率'],
    relatedStocks: [
      { code: '601398', name: '工商银行' },
      { code: '600036', name: '招商银行' },
      { code: '601166', name: '兴业银行' },
    ],
  },

  // 6. 全球外盘期货
  {
    symbol: 'hf_CL',
    name: 'WTI原油连续',
    category: '外盘期货',
    subCategory: '全球大宗',
    exchange: 'NYMEX',
    unit: '美元/桶',
    isGlobal: true,
    relatedSectors: ['国际油价', '原油QDII', '油服工程', '石化产业链'],
    relatedStocks: [
      { code: '600938', name: '中国海油' },
      { code: '601857', name: '中国石油' },
      { code: '603619', name: '中曼石油' },
    ],
  },
  {
    symbol: 'hf_GC',
    name: 'COMEX纽约黄金',
    category: '外盘期货',
    subCategory: '全球大宗',
    exchange: 'COMEX',
    unit: '美元/盎司',
    isGlobal: true,
    relatedSectors: ['国际金价', '黄金避险', '黄金ETF'],
    relatedStocks: [
      { code: '600547', name: '山东黄金' },
      { code: '601899', name: '紫金矿业' },
      { code: '600489', name: '中金黄金' },
    ],
  },
  {
    symbol: 'hf_CAD',
    name: 'LME伦铜连续',
    category: '外盘期货',
    subCategory: '全球大宗',
    exchange: 'LME',
    unit: '美元/吨',
    isGlobal: true,
    relatedSectors: ['全球铜价', '宏观工业晴雨表', '有色铜采选'],
    relatedStocks: [
      { code: '600362', name: '江西铜业' },
      { code: '601899', name: '紫金矿业' },
      { code: '601168', name: '西部矿业' },
    ],
  },
  {
    symbol: 'hf_NQ',
    name: '纳斯达克100期指',
    category: '外盘期货',
    subCategory: '全球股指',
    exchange: 'CME',
    unit: '点',
    isGlobal: true,
    relatedSectors: ['美股科技', 'AI硬件算力', '半导体产业链', '纳指ETF'],
    relatedStocks: [
      { code: '600487', name: '亨通光电' },
      { code: '300017', name: '网宿科技' },
      { code: '603083', name: '剑桥科技' },
      { code: '603629', name: '利通电子' },
    ],
  },
];
