export interface SectorItem {
  code: string; // e.g. "BK_DKJJ", "BK_SEMICONDUCTOR", "BK_AI_POWER"
  bkCode: string; // Eastmoney BK Code, e.g. "BK1166", "BK0980", "BK1128"
  name: string; // e.g. "低空经济", "半导体芯片", "算力与AI"
  category: '主线题材' | '高景气制造' | '核心资产' | '周期资源' | '金融消费';
  description: string;
  leadStockCode: string;
  leadStockName: string;
  constituents: { code: string; name: string; isLeader?: boolean }[];
  catalyst: string;
}

export const SECTOR_DATABASE: SectorItem[] = [
  {
    code: 'BK_DKJJ',
    bkCode: 'BK1166',
    name: '低空经济',
    category: '主线题材',
    description: 'eVTOL电动垂直起降航空器、低空空域管制作战系统、无人机物流与通航基础设施。',
    leadStockCode: '300862',
    leadStockName: '蓝盾光电',
    catalyst: '多省市低空经济行动方案加速落地，低空空域空管系统与eVTOL适航取证进入密集突破期。',
    constituents: [
      { code: '300862', name: '蓝盾光电', isLeader: true },
      { code: '002085', name: '万丰奥威' },
      { code: '000099', name: '中信海直' },
      { code: '300034', name: '钢研高纳' },
      { code: '600372', name: '中航机载' },
      { code: '300696', name: '爱乐达' },
      { code: '688286', name: '敏芯股份' },
    ],
  },
  {
    code: 'BK_SEMICONDUCTOR',
    bkCode: 'BK0980',
    name: '半导体芯片',
    category: '高景气制造',
    description: '先进光刻胶、存储芯片、封测设备、EDA软件及高端功率半导体国产化替代。',
    leadStockCode: '688286',
    leadStockName: '敏芯股份',
    catalyst: '全球半导体周期强劲复苏，AI服务器对高带宽存储(HBM)及先进封装需求爆发。',
    constituents: [
      { code: '688286', name: '敏芯股份', isLeader: true },
      { code: '688662', name: '富信科技' },
      { code: '300684', name: '中石科技' },
      { code: '688981', name: '中芯国际' },
      { code: '603986', name: '兆易创新' },
      { code: '600584', name: '长电科技' },
      { code: '002049', name: '紫光国微' },
    ],
  },
  {
    code: 'BK_AI_POWER',
    bkCode: 'BK1128',
    name: '算力与CPO光模块',
    category: '主线题材',
    description: '智算中心IDC、CPO光模块、液冷服务器、光纤光缆与大模型端侧部署。',
    leadStockCode: '300017',
    leadStockName: '网宿科技',
    catalyst: '全球云巨头AI资本开支(Capex)持续大幅上调，800G/1.6T高速光模块进入放量周期。',
    constituents: [
      { code: '300017', name: '网宿科技', isLeader: true },
      { code: '600487', name: '亨通光电' },
      { code: '603083', name: '剑桥科技' },
      { code: '603629', name: '利通电子' },
      { code: '300308', name: '中际旭创' },
      { code: '300502', name: '新易盛' },
      { code: '600941', name: '中国移动' },
    ],
  },
  {
    code: 'BK_ROBOT',
    bkCode: 'BK1090',
    name: '人形机器人',
    category: '高景气制造',
    description: '行星滚柱丝杠、六维力传感器、空心杯电机、减速器与具身智能大模型。',
    leadStockCode: '688485',
    leadStockName: '九州一轨',
    catalyst: '特斯拉Optimus量产进程提速，国内具身智能机器人产业政策密集催化。',
    constituents: [
      { code: '688485', name: '九州一轨', isLeader: true },
      { code: '300024', name: '机器人' },
      { code: '002896', name: '中大力德' },
      { code: '603728', name: '鸣志电器' },
      { code: '002472', name: '双环传动' },
      { code: '300124', name: '汇川技术' },
      { code: '603200', name: '上海瀚讯' },
    ],
  },
  {
    code: 'BK_BATTERY',
    bkCode: 'BK0968',
    name: '固态电池与锂电',
    category: '高景气制造',
    description: '全固态电解质、高镍三元正极、硅碳负极、电池级碳酸锂与储能系统。',
    leadStockCode: '603330',
    leadStockName: '天洋新材',
    catalyst: '全固态电池能量密度与装车验证取得重大突破，主流车企宣布2026年量产计划。',
    constituents: [
      { code: '603330', name: '天洋新材', isLeader: true },
      { code: '300750', name: '宁德时代' },
      { code: '002466', name: '天齐锂业' },
      { code: '002460', name: '赣锋锂业' },
      { code: '300014', name: '亿纬锂能' },
      { code: '002709', name: '天赐材料' },
    ],
  },
  {
    code: 'BK_AUTO',
    bkCode: 'BK0481',
    name: '智能汽车与零部件',
    category: '高景气制造',
    description: '智能座舱、自动驾驶域控制器、汽车轻量化饰件、线控底盘。',
    leadStockCode: '001260',
    leadStockName: '坤泰股份',
    catalyst: 'L3级高阶智驾试点落地，新能源汽车以旧换新补贴政策加码刺激销量。',
    constituents: [
      { code: '001260', name: '坤泰股份', isLeader: true },
      { code: '600660', name: '福耀玻璃' },
      { code: '601799', name: '星宇股份' },
      { code: '600699', name: '均胜电子' },
      { code: '002594', name: '比亚迪' },
      { code: '601633', name: '长城汽车' },
    ],
  },
  {
    code: 'BK_SECURITIES',
    bkCode: 'BK0473',
    name: '证券券商与金融',
    category: '金融消费',
    description: '头部券商整合并购、财富管理、衍生品交易与资本市场改革红利。',
    leadStockCode: '600030',
    leadStockName: '中信证券',
    catalyst: '资本市场深化改革，一流投资银行建设与头部券商重组预期强化。',
    constituents: [
      { code: '600030', name: '中信证券', isLeader: true },
      { code: '601788', name: '光大证券' },
      { code: '600999', name: '招商证券' },
      { code: '300059', name: '东方财富' },
      { code: '601211', name: '国泰君安' },
      { code: '601688', name: '华泰证券' },
    ],
  },
  {
    code: 'BK_RARE_EARTH',
    bkCode: 'BK0578',
    name: '稀土永磁与新材料',
    category: '周期资源',
    description: '高性能钕铁硼永磁材料、重稀土配额管控、新能源电机与军工配套。',
    leadStockCode: '000831',
    leadStockName: '中国稀土',
    catalyst: '稀土管理条例落地实施，供需格局持续改善带动氧化镨钕价格稳步反弹。',
    constituents: [
      { code: '000831', name: '中国稀土', isLeader: true },
      { code: '600111', name: '北方稀土' },
      { code: '600366', name: '宁波韵升' },
      { code: '300224', name: '正海磁材' },
      { code: '600330', name: '金力永磁' },
    ],
  },
  {
    code: 'BK_MEDICAL',
    bkCode: 'BK0465',
    name: '医疗服务与医药',
    category: '核心资产',
    description: '创新药出海、医美康养、医疗服务、中药创新与医疗器械。',
    leadStockCode: '002172',
    leadStockName: '澳洋健康',
    catalyst: '创新药全链条支持政策发布，出海授权(License-out)交易金额频创新高。',
    constituents: [
      { code: '002172', name: '澳洋健康', isLeader: true },
      { code: '600276', name: '恒瑞医药' },
      { code: '300760', name: '迈瑞医疗' },
      { code: '603259', name: '药明康德' },
      { code: '300015', name: '爱尔眼科' },
      { code: '000538', name: '云南白药' },
    ],
  },
  {
    code: 'BK_LIQUOR',
    bkCode: 'BK0493',
    name: '白酒与高端消费',
    category: '核心资产',
    description: '高端酱香白酒、次高端浓香白酒、品牌消费品。',
    leadStockCode: '600519',
    leadStockName: '贵州茅台',
    catalyst: '中秋国庆旺季备货启动，头部酒企控量挺价强化经营韧性。',
    constituents: [
      { code: '600519', name: '贵州茅台', isLeader: true },
      { code: '000858', name: '五粮液' },
      { code: '000568', name: '泸州老窖' },
      { code: '600809', name: '山西汾酒' },
      { code: '002304', name: '洋河股份' },
      { code: '600779', name: '水井坊' },
    ],
  },
  {
    code: 'BK_AEROSPACE',
    bkCode: 'BK1173',
    name: '商业航天与卫星',
    category: '主线题材',
    description: '低轨卫星互联网、千帆星座组网、可回收液体运载火箭与星载相控阵雷达。',
    leadStockCode: '600118',
    leadStockName: '中国卫星',
    catalyst: '我国商业航天千帆极轨星座发射提速，卫星互联网地面终端规模化商用加速。',
    constituents: [
      { code: '600118', name: '中国卫星', isLeader: true },
      { code: '603200', name: '上海瀚讯' },
      { code: '300053', name: '航天发展' },
      { code: '688568', name: '中科星图' },
      { code: '600879', name: '航天电子' },
    ],
  },
  {
    code: 'BK_ENERGY_STORAGE',
    bkCode: 'BK0989',
    name: '光伏与新型储能',
    category: '高景气制造',
    description: '大储电站EPC、工商业储能、TOPCon/HJT光伏电池组件、微逆变器。',
    leadStockCode: '300274',
    leadStockName: '阳光电源',
    catalyst: '全球大储需求爆发，储能电芯价格企稳，海外微电网与工商业储能装机量高增。',
    constituents: [
      { code: '300274', name: '阳光电源', isLeader: true },
      { code: '601012', name: '隆基绿能' },
      { code: '600438', name: '通威股份' },
      { code: '601877', name: '正泰电器' },
      { code: '300763', name: '锦浪科技' },
    ],
  },
];

